package com.project.figureout.model;

public enum SaleStatusEnum {
    EM_PROCESSAMENTO,
    PAGAMENTO_REJEITADO,
    PAGAMENTO_REALIZADO,
    EM_TRANSPORTE,
    ENTREGUE,
    TROCA_SOLICITADA,
    TROCA_NAO_AUTORIZADA,
    TROCA_AUTORIZADA,
    EM_TROCA,
    TROCA_RECEBIDA,
    TROCA_FINALIZADA
}
